name: iapp_player_example
description: Example app for IAppPlayer
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  iapp_player:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  wakelock_plus: ^1.2.10  
  intl: ^0.20.2
  meta: ^1.12.0
  flutter_widget_from_html_core: ^0.15.1
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.5      
  collection: ^1.18.0
  xml: 6.5.0     

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/videos/
    - assets/subtitles/
    - assets/music/
    - assets/lyrics/
    - assets/images/
  uses-material-design: true
